#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(expm)
library(plotly)
library(ggplot2)
library(ggplotify)
library(graphics)

GetTrueProbsAsymm = function(myt1,myt2,myt3,theta,alpha) {
    
    #these get us the site pattern frequencies that match the data sets generated by the seq-gen pipeline
    t1 = myt1*theta  # t1*theta
    t2 = myt2*theta  # t2*theta
    t3 = myt3*theta  # t3*theta
    t = 2*theta      # 2*theta
    m = alpha        # mu for JC69
    
    #compute the C matrix
    cmat = matrix(0,ncol=10,nrow=11)
    # row 1
    cmat[1,1] = 1/256
    cmat[1,2] = 3/((256)*(1+m*t))
    cmat[1,3] = 6/(256*(1+m*t))
    cmat[1,4] = 12/(256*(1+m*t)*(2+m*t))
    cmat[1,5] = 9/(256*(1+m*t))
    cmat[1,6] = 12/(256*(1+m*t)*(2+m*t))
    cmat[1,7] = 9/(256*(1+m*t)^2)
    cmat[1,8] = 24/(256*(1+m*t)*(2+m*t))
    cmat[1,9] = 48/(256*(1+m*t)*(2+m*t)^2)
    cmat[1,10] = (6*m*t*(4+m*t)*(4+3*m*t))/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    # row 2
    cmat[2,1] = 1/256
    cmat[2,2] = -1/(256*(1+m*t))
    cmat[2,3] = 2/(256*(1+m*t))
    cmat[2,4] = -4/(256*(1+m*t)*(2+m*t))
    cmat[2,5] = 5/(256*(1+m*t))
    cmat[2,6] = -4/(256*(1+m*t)*(2+m*t))
    cmat[2,7] = -3/(256*(1+m*t)^2)
    cmat[2,8] = 8/(256*(1+m*t)*(2+m*t))
    cmat[2,9] = -16/(256*(1+m*t)*(2+m*t)^2)
    cmat[2,10] = -(2*m*t*(4+m*t)*(4+3*m*t))/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    # row 3
    cmat[3,1] = 1/256
    cmat[3,2] = 3/(256*(1+m*t))
    cmat[3,3] = -2/(256*(1+m*t))
    cmat[3,4] = -4/(256*(1+m*t)*(2+m*t))
    cmat[3,5] = 5/(256*(1+m*t))
    cmat[3,6] = 12/(256*(1+m*t)*(2+m*t))
    cmat[3,7] = -3/(256*(1+m*t)^2)
    cmat[3,8] = -8/(256*(1+m*t)*(2+m*t))
    cmat[3,9] = -16/(256*(1+m*t)*(2+m*t)^2)
    cmat[3,10] = -(2*m*t*(4+m*t)*(4+3*m*t))/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    # row 4
    cmat[4,1] = 1/256
    cmat[4,2] = 3/(256*(1+m*t))
    cmat[4,3] = 6/(256*(1+m*t))
    cmat[4,4] = 12/(256*(1+m*t)*(2+m*t))
    cmat[4,5] = -3/(256*(1+m*t))
    cmat[4,6] = -4/(256*(1+m*t)*(2+m*t))
    cmat[4,7] = -3/(256*(1+m*t)^2)
    cmat[4,8] = -8/(256*(1+m*t)*(2+m*t))
    cmat[4,9] = -16/(256*(1+m*t)*(2+m*t)^2)
    cmat[4,10] = -(2*m*t*(4+m*t)*(4+3*m*t))/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    #row 5
    cmat[5,1] = 1/256
    cmat[5,2] = 3/((256)*(1+m*t))
    cmat[5,3] = -2/((256)*(1+m*t))
    cmat[5,4] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[5,5] = 1/((256)*(1+m*t))
    cmat[5,6] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[5,7] = 9/((256)*(1+m*t)^2)
    cmat[5,8] = -8/((256)*(1+m*t)*(2+m*t))
    cmat[5,9] = -16/((256)*(1+m*t)*(2+m*t)^2)
    cmat[5,10] = (2*m*t*(4+m*t)^2)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    # row 6
    cmat[6,1] = 1/256
    cmat[6,2] = -1/((256)*(1+m*t))
    cmat[6,3] = 2/((256)*(1+m*t))
    cmat[6,4] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[6,5] = 1/((256)*(1+m*t))
    cmat[6,6] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[6,7] = 1/((256)*(1+m*t)^2)
    cmat[6,8] = -8/((256)*(1+m*t)*(2+m*t))
    cmat[6,9] = 16/((256)*(1+m*t)*(2+m*t)^2)
    cmat[6,10] = m*t*(2*16+40*m*t+(10)*(m^2)*(t^2))/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    # row 7
    cmat[7,1] = 1/256
    cmat[7,2] = -1/((256)*(1+m*t))
    cmat[7,3] = -2/((256)*(1+m*t))
    cmat[7,4] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[7,5] = 1/((256)*(1+m*t))
    cmat[7,6] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[7,7] = -3/((256)*(1+m*t)^2)
    cmat[7,8] = -8/((256)*(1+m*t)*(2+m*t))
    cmat[7,9] = 16/((256)*(1+m*t)*(2+m*t)^2)
    cmat[7,10] = 2*(m^2)*(t^2)*(4+m*t)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    # row 8
    cmat[8,1] = 1/256
    cmat[8,2] = 3/((256)*(1+m*t))
    cmat[8,3] = -2/((256)*(1+m*t))
    cmat[8,4] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[8,5] = -3/((256)*(1+m*t))
    cmat[8,6] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[8,7] = -3/((256)*(1+m*t)^2)
    cmat[8,8] = 8/((256)*(1+m*t)*(2+m*t))
    cmat[8,9] = 16/((256)*(1+m*t)*(2+m*t)^2)
    cmat[8,10] = 2*(m^2)*(t^2)*(4+m*t)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    # row 9
    cmat[9,1] = 1/256
    cmat[9,2] = -1/((256)*(1+m*t))
    cmat[9,3] = -2/((256)*(1+m*t))
    cmat[9,4] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[9,5] = 1/((256)*(1+m*t))
    cmat[9,6] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[9,7] = 1/((256)*(1+m*t)^2)
    cmat[9,8] = 0
    cmat[9,9] = 0
    cmat[9,10] = -(m^2)*(t^2)*(4+2*m*t)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    # row 10
    cmat[10,1] = 1/256
    cmat[10,2] = -1/((256)*(1+m*t))
    cmat[10,3] = 2/((256)*(1+m*t))
    cmat[10,4] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[10,5] = -3/((256)*(1+m*t))
    cmat[10,6] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[10,7] = 1/((256)*(1+m*t)^2)
    cmat[10,8] = 0
    cmat[10,9] = 0
    cmat[10,10] = -(m^2)*(t^2)*(4+2*m*t)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    # row 11
    cmat[11,1] = 1/256
    cmat[11,2] = -1/((256)*(1+m*t))
    cmat[11,3] = -2/((256)*(1+m*t))
    cmat[11,4] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[11,5] = -3/((256)*(1+m*t))
    cmat[11,6] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[11,7] = 1/((256)*(1+m*t)^2)
    cmat[11,8] = 8/((256)*(1+m*t)*(2+m*t))
    cmat[11,9] = -16/((256)*(1+m*t)*(2+m*t)^2)
    cmat[11,10] = 2*(m^3)*(t^3)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    
    
    #get the beta vector
    beta = matrix(0,ncol=1,nrow=10)
    beta[1,1]=1
    beta[2,1]=exp(-2*m*t1)
    beta[3,1]=exp(-2*m*t2)
    beta[4,1]=exp(-m*t1)*exp(-2*m*t2)
    beta[5,1]=exp(-2*m*t3)
    beta[6,1]=exp(-m*t1)*exp(-2*m*t3)
    beta[7,1]=exp(-2*m*t1)*exp(-2*m*t3)
    beta[8,1]=exp(-m*t2)*exp(-2*m*t3)
    beta[9,1]=exp(-m*t1)*exp(-m*t2)*exp(-2*m*t3)
    beta[10,1]=exp((2/t)*(t1-t2))*exp(-2*m*(t2+t3))
    
    weights=matrix(0,ncol=11,nrow=1)
    w1=weights[1,1]=4
    w2=weights[1,2]=24
    w3=weights[1,3]=12
    w4=weights[1,4]=12
    w5=weights[1,5]=12
    w6=weights[1,6]=24
    w7=weights[1,7]=24
    w8=weights[1,8]=24
    w9=weights[1,9]=48
    w10=weights[1,10]=48
    w11=weights[1,11]=24
    
    
    p=cmat%*%beta
    return(p)
}


# Define UI for application that draws a histogram
ui <- fluidPage(
    
    # Application title
    titlePanel("Site Pattern Probability Calculator"),
    
    # Sidebar with a slider input for number of bins 
    sidebarLayout(
        sidebarPanel(
            sliderInput("length1",
                        "Branch length 1 in coalescent units:",
                        min = 0.001,
                        max = 10.0,
                        value = 2.0),
            sliderInput("length2",
                        "Branch length 2 in coalescent units:",
                        min = 0.001,
                        max = 10.0,
                        value = 2.0),
            sliderInput("length3",
                        "Branch length 3 in coalescent units:",
                        min = 0.001,
                        max = 10.0,
                        value = 2.0),
            sliderInput("theta",
                        "Effective population size (4Nu):",
                        min = 0.0001,
                        max = 0.5,
                        value = 0.01),
            br(),
            h4("The species tree for which site pattern probabilities will be computed is shown below. Use the sliders above to adjust the branch lengths and the effective population size."),
            br(),
            img(src='SpeciesTree.png',height="60%", width="60%",align = "center"),
            br(),
            br(),
            
        ),
        
        # Show a plot of the generated distribution
        mainPanel(plotOutput(outputId="SitePatternProbPlot"),
                  br(),
                  tags$h5("Site patterns are given in the order of species in the tree from left to right. For example, the pattern 'xyzw' refers to the observation that species A has nucleotide x, species B has nucleotide y, species C has nucleotide z, and species D has nucleotide w, where x, y, z, and w are all distinct nucleotides. All calculations assume the JC69 model.",style="color:steelblue"),
                  tags$h5("The pattern 'xxxx' refers to the constant site pattern, i.e., the height of this bar gives the probability of observing that all species have nucleotide A, for example. Since there are four patterns that match 'xxxx' (i.e., AAAA, CCCC, TTTT, GGGG), the overall probability of getting a constant site pattern will be 4 times the height of this bar.",style="color:steelblue"),
                  #plotOutput(outputId="GeneTreeProbPlotWeighted"),
                  tags$h5("Note that the symmetry between species C and D results in some site pattern probabilities being equal. Taking this into account, the number of sites for each generic pattern above is as follows:"),
                  pre("xxxx: 4              xxyz: 24  
xxxy = xxyx: 24      yzxx: 24      
xyxx: 12             xyxz = xyzx: 48
yxxx: 12             yxxz = yxzx: 48
xxyy: 12             xyzw: 24
xyxy = xyyx: 24")
                  
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
    
    output$SitePatternProbPlot <- renderPlot({
        # generate bins based on input$bins from ui.R
        patterns = c("xxxx","xxxy","xyxx","yxxx","xxyy","xyxy","xxyz","yzxx","xyxz","yxxz","xyzw")
        
        bl1 = input$length1
        bl2 = input$length2
        bl3 = input$length3
        th = input$theta
        
        pp=GetTrueProbsAsymm(bl3,bl3+bl2,bl3+bl2+bl1,th/2,4.0/3.0)
        probs = c(pp[1],pp[2],pp[3],pp[4],pp[5],pp[6],pp[7],pp[8],pp[9],pp[10],pp[11])
        
        probdist = data.frame(cbind(patterns,probs))
        probdist$probs <-as.numeric(probdist$probs)
        probdist$patterns <-factor(probdist$patterns,levels=c("xxxx","xxxy","xyxx","yxxx","xxyy","xyxy","xxyz","yzxx","xyxz","yxxz","xyzw"))
      
        
        p<-ggplot(data=probdist, aes(x=patterns, y=probs)) +
            geom_col(fill="steelblue")+
            theme(axis.text.x = element_text(angle = 0,),axis.text=element_text(size=20),
                  axis.title=element_text(size=18,face="bold"), title=element_text(size=18, face='bold'))+expand_limits(y=c(0,max(probs))) +
            xlab("Site Pattern") + ylab("Probability") +
            ggtitle("Site pattern probabilities under the multispecies coalescent")
        p
    })
    
    
    output$GeneTreeProbPlotWeighted <- renderPlot({
        # generate bins based on input$bins from ui.R
        patterns = c("xxxx","xxxy","xyxx","yxxx","xxyy","xyxy","xxyz","yzxx","xyxz","yxxz","xyzw")
        
        bl1 = input$length1
        bl2 = input$length2
        bl3 = input$length3
        th = input$theta
        
        pp=GetTrueProbsAsymm(bl3,bl3+bl2,bl3+bl2+bl1,th/2,4.0/3.0)
        probs2 = c(4*pp[1],24*pp[2],12*pp[3],12*pp[4],12*pp[5],24*pp[6],24*pp[7],24*pp[8],48*pp[9],48*pp[10],24*pp[11])
        
        probdist = data.frame(cbind(patterns,probs2))
        probdist$probs2 <-as.numeric(probdist$probs2)
        probdist$patterns <-factor(probdist$patterns,levels=c("xxxx","xxxy","xyxx","yxxx","xxyy","xyxy","xxyz","yzxx","xyxz","yxxz","xyzw"))
        
        
        p2<-ggplot(data=probdist, aes(x=patterns, y=probs2)) +
            geom_col(fill="maroon")+
            theme(axis.text.x = element_text(angle = 0,),axis.text=element_text(size=20),
                  axis.title=element_text(size=18,face="bold"), title=element_text(size=18, face='bold'))+expand_limits(y=c(0,max(probs2))) +
            xlab("Site Pattern") + ylab("Probability") +
            ggtitle("Weighted site pattern probabilities  under the multispecies coalescent")
        p2
    })
    
}

# Run the application 
shinyApp(ui = ui, server = server)
